# 第2章 Numpy数组

## 2.1 Numpy数组对象

In [2]:
import numpy as np

In [3]:
a=np.arange(5)

In [5]:
a.dtype

dtype('int32')

In [6]:
a

array([0, 1, 2, 3, 4])

In [7]:
a.shape

(5L,)

## 2.2 创建多维数组

In [11]:
m=np.array([np.arange(2),np.arange(2)])

In [12]:
m

array([[0, 1],
       [0, 1]])

In [13]:
m.shape

(2L, 2L)

## 2.3 选择Numpy数组元素

In [18]:
a=np.array([[1,2],[3,4]])

In [19]:
a

array([[1, 2],
       [3, 4]])

In [22]:
a[0,0]

1

In [21]:
a[0,1]

2

In [23]:
a[1,0]

3

In [24]:
a[1,1]

4

## 2.4 Numpy的数值类型

In [26]:
np.float64(42)

42.0

In [27]:
np.int8(42.0)

42

In [28]:
np.bool(42)

True

In [29]:
np.bool(0)

False

In [30]:
np.bool(42.0)

True

In [31]:
np.float(True)

1.0

In [32]:
np.float(False)

0.0

### 2.4.1 数据类型对象

In [33]:
a.dtype.itemsize

4

### 2.4.2 字符码

In [35]:
np.arange(7,dtype='f')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.], dtype=float32)

In [36]:
np.arange(7,dtype='D')

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j])

### 2.4.3 Dtype构造函数

In [37]:
np.dtype(float)

dtype('float64')

In [38]:
np.dtype('f')

dtype('float32')

In [39]:
np.dtype('d')

dtype('float64')

In [40]:
np.dtype('f8')

dtype('float64')

In [42]:
np.sctypeDict.keys()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 'unicode',
 23,
 'cfloat',
 'longfloat',
 'Int32',
 'Complex64',
 'unicode_',
 'complex',
 'timedelta64',
 'uint16',
 'c16',
 'float32',
 'int32',
 'D',
 'H',
 'void',
 'unicode0',
 'L',
 'P',
 'half',
 'void0',
 'd',
 'h',
 'l',
 'p',
 22,
 'Timedelta64',
 'object0',
 'b1',
 'M8',
 'String0',
 'float16',
 'ulonglong',
 'i1',
 'uint32',
 '?',
 'Void0',
 'complex64',
 'G',
 'O',
 'UInt8',
 'S',
 'byte',
 'UInt64',
 'g',
 'float64',
 'ushort',
 'float_',
 'uint',
 'object_',
 'Float16',
 'complex_',
 'Unicode0',
 'uintp',
 'intc',
 'csingle',
 'datetime64',
 'float',
 'bool8',
 'Bool',
 'intp',
 'uintc',
 'bytes_',
 'u8',
 'u4',
 'int_',
 'cdouble',
 'u1',
 'complex128',
 'u2',
 'f8',
 'Datetime64',
 'ubyte',
 'm8',
 'B',
 'uint0',
 'F',
 'bool_',
 'uint8',
 'c8',
 'Int64',
 'Int8',
 'Complex32',
 'V',
 'int8',
 'uint64',
 'b',
 'f',
 'double',
 'UInt32',
 'clongdouble',
 'str',
 'f2',
 '

### 2.4.4 dtype属性

In [43]:
t=np.dtype('Float64')

In [44]:
t.char

'd'

## 2.5 一维数组的切片与索引

In [50]:
a=np.arange(9)

In [51]:
a[3:7]

array([3, 4, 5, 6])

In [52]:
a[:7:2]

array([0, 2, 4, 6])

In [53]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2.6 处理数组形状

In [54]:
b=np.arange(24).reshape(2,3,4)

In [55]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
b.shape=(6,4)

In [61]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [63]:
b.resize(2,12)

In [64]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [67]:
b.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [68]:
a=np.arange(9).reshape(3,3)

### 2.6.1 堆叠数组

In [69]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
b=a*2

In [71]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [74]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [76]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [83]:
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [75]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [77]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [84]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [78]:
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

### 2.6.2 拆分Numpy数组

In [86]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [88]:
np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [87]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [89]:
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

### 2.6.3 Numpy数组的属性

In [93]:
b=np.arange(24).reshape(2,12)

In [94]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [95]:
b.ndim

2

In [96]:
b.size

24

In [97]:
b.nbytes

96

In [98]:
b.resize(4,6)

In [99]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [100]:
b.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [101]:
b.ndim

2

In [105]:
b.flat[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### 2.6.4 数组的转换

In [106]:
b.tolist()

[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [107]:
b.astype('f')

array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.,  16.,  17.],
       [ 18.,  19.,  20.,  21.,  22.,  23.]], dtype=float32)

## 2.7 创建数组的视图合拷贝

In [140]:
import scipy.misc
import matplotlib.pyplot as plt

In [147]:
lena = misc.face()
acopy=scipy.misc.face()
aview=lena.view()

In [143]:
plt.subplot(221)
plt.imshow(lena)
plt.subplot(222)
plt.imshow(acopy)
plt.subplot(223)
plt.imshow(aview)
aview.flat=0
plt.subplot(224)
plt.imshow(aview)
plt.show()
plt.show()

## 2.8 花式索引

In [148]:
import scipy.misc
import matplotlib.pyplot as plt

In [156]:
face=scipy.misc.face()
l=(face.shape[1]-face.shape[0])/2
face=face[:,0+l:-l]
xmax,ymax=face.shape[0],face.shape[1]

In [157]:
xmax,ymax

(768L, 768L)

In [159]:
face[range(xmax),range(ymax)]=0

In [166]:
face[range(xmax-1,-1,-1),range(ymax)]=0

In [168]:
plt.imshow(face)
plt.show()

## 2.9 基于位置列表的索引方法

In [170]:
a=np.arange(36).reshape(6,-1)

In [171]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [172]:
a[[1,3],[2,4]]

array([ 8, 22])

## 2.10 用布尔型变量索引Numpy数组

In [174]:
b=np.zeros((6,6),dtype=int)

In [186]:
b[[1,3],[2,4]]=1
b=b.astype(bool)

In [187]:
a[b]

array([ 8, 22])

## 2.11 Numpy数组广播

假设一个数组要跟一个标量相乘，这是标量需要根据数组的形状进行扩展，然后才可以执行乘法运算，这个扩展的过程叫做广播。