# 第6章 数据可视化

## 6.1 matplotlib的子库

In [1]:
import matplotlib as mpl

In [3]:
mpl.__version__

'1.5.1'

In [4]:
mpl.__path__

['E:\\Anaconda2\\lib\\site-packages\\matplotlib']

## 6.2 matplotlib绘图入门

In [8]:
import matplotlib.pyplot as plt
import numpy as np

In [10]:
x=np.linspace(0,20)

In [11]:
plt.plot(x,x+0.5)

In [12]:
plt.plot(x,x**2+1,'--')

In [14]:
plt.show()

## 6.3 对数图

In [15]:
import pandas as pd

In [22]:
df=pd.read_csv('data/transcount.csv')

In [23]:
df

trans_count  year
0    2600000000  2011
1    4310000000  2014
2    1000000000  2010
3    5000000000  2012
4    1200000000  2012
5    3100000000  2012
6    1200000000  2010
7    2100000000  2012
8    2300000000  2010
9     463000000  2007
10    758000000  2008
11      4300000  1996
12      8800000  1997
13     21300000  1999
14     22000000  1999
15    105900000  2003
16        25000  1985
17        25000  1986
18       300000  1989
19        30000  1991
20       578977  1994
21     26000000  2007
22     47000000  2008
23     54300000  2003
24    241000000  2006
25    169000000  2007
26    291000000  2006
27    411000000  2007
28    230000000  2008
29    731000000  2008
..          ...   ...
51      3100000  1993
52    184000000  2006
53     55000000  2002
54    112000000  2004
55    169000000  2005
56     42000000  2000
57      7500000  1998
58      7500000  1997
59     21000000  2000
60      9500000  1999
61     45000000  2001
62      5500000  1995
63    789000000  2007
64   1303000000  2012
65   1160000000  2011
66   1400000000  2012
67   2000000000  2010
68   1400000000  2010
69      1350000  1991
70         5000  1974
71   1170000000  2010
72   2270000000  2011
73    904000000  2011
74   1900000000  2009
75   2750000000  2008
76       785000  2012
77   5000000000  2009
78         8500  1983
79   5000000000  2013
80         8500  1976

[81 rows x 2 columns]

In [24]:
df=df.groupby('year').aggregate(np.mean)

In [25]:
df

trans_count
year              
1971  2.300000e+03
1972  3.500000e+03
1974  4.533333e+03
1975  3.510000e+03
1976  7.500000e+03
1978  1.900000e+04
1979  4.850000e+04
1982  9.450000e+04
1983  8.500000e+03
1984  2.000000e+05
1985  1.053333e+05
1986  2.500000e+04
1988  2.500000e+05
1989  7.401175e+05
1991  6.900000e+05
1993  3.100000e+06
1994  5.789770e+05
1995  5.500000e+06
1996  4.300000e+06
1997  8.150000e+06
1998  7.500000e+06
1999  1.760000e+07
2000  3.150000e+07
2001  4.500000e+07
2002  1.375000e+08
2003  1.900667e+08
2004  3.520000e+08
2005  1.690000e+08
2006  6.040000e+08
2007  3.716000e+08
2008  9.032000e+08
2009  3.450000e+09
2010  1.511667e+09
2011  1.733500e+09
2012  2.014826e+09
2013  5.000000e+09
2014  4.310000e+09

In [32]:
years=df.index.values

In [33]:
counts=df['trans_count'].values

In [36]:
ploy=np.polyfit(years,np.log(counts),deg=1)

In [37]:
plt.semilogy(years,counts,'o')

In [39]:
plt.semilogy(years,np.exp(np.polyval(ploy,years)))

In [41]:
plt.show()

In [42]:
ploy

array([  3.61559210e-01,  -7.05783195e+02])

## 6.4 散点图

In [44]:
x=np.random.randn(10)

In [45]:
y=np.random.randn(10)

In [46]:
x

array([ 0.8714836 , -2.5937808 , -0.28279329,  0.54284922, -0.29154632,
       -0.09974526, -1.00077816, -0.50220166,  0.40760248, -0.02017297])

In [47]:
y

array([-0.62359266, -0.76717441, -2.78535327, -1.34417792, -0.61728962,
       -0.45703388,  0.89025566,  1.28509065, -0.38602817, -0.38312669])

In [55]:
plt.scatter(x,y,c=200*x,s=20+30*y/y.max(),alpha=0.5)
plt.show()

## 6.5 图例和注解

In [57]:
x=np.random.randn(100)

In [58]:
y=np.random.randn(100)

In [59]:
x

array([ 0.0426839 ,  0.7820998 , -0.39084045, -0.06431172, -1.29302721,
       -0.42250475, -2.16666998,  0.74927486,  0.37931892,  1.00512378,
        2.38614917,  2.05991719, -1.34539382,  0.74818753,  0.85543166,
        0.80225555, -1.29382791,  0.03265589, -0.83613661, -0.24687071,
       -1.0954847 , -1.43867527,  0.84747448, -0.91841297,  1.0404572 ,
       -0.34616863, -0.10796286,  0.96730471,  0.54438811, -0.63538422,
       -2.05582088, -0.33738082, -0.13259082,  1.65104255, -1.47029884,
        1.03585343, -0.64607655,  0.01327054, -0.97760217, -1.51038344,
        0.70857568,  0.96903416,  0.0531329 , -1.14737194, -1.5314476 ,
        1.1855453 ,  0.50392124, -0.33242534, -1.30506534, -2.12068067,
       -0.98579496, -0.02245876,  0.55815238, -0.53385057, -0.80380769,
        0.08369835,  0.53128638, -0.09043645,  1.21671011,  0.13291395,
        0.26958188, -2.17037959,  0.77622489,  0.63970691,  1.74673164,
        0.08638583,  0.77750915,  0.31778703,  0.32692813,  0.51

In [60]:
y

array([ 1.23569103, -1.09302854, -0.4574078 ,  0.58222895, -0.98175295,
        1.35197259,  0.57233268,  0.44514902,  0.18070953, -1.08283873,
        0.67770657, -0.63181694, -0.38270423,  0.46794264, -1.48252801,
        0.6481097 , -2.64105796,  0.88554377, -0.1357911 , -1.30953668,
        1.67659297, -0.38980712, -0.20838157, -1.87705235,  0.55336613,
       -0.27618934,  1.35546758, -0.52420246,  0.2507974 , -1.61864394,
       -0.71457188, -0.18971088, -0.85352858,  1.51140476,  0.08785152,
       -0.35381679,  0.56926579,  0.76073636,  0.13409738,  0.26079957,
       -1.11821477,  0.55831362,  0.11182753, -1.15315411, -0.3877053 ,
        0.699293  , -0.33075202, -0.3905037 ,  1.86478661, -1.37254325,
        1.07522606, -0.76252483, -0.21903287,  0.58269616,  0.12824843,
       -0.80855857,  0.3383175 , -0.69050992, -0.31459908, -1.30759782,
        0.5887067 ,  0.70552566, -0.26024564,  0.54170632,  0.80399891,
        0.47259073, -0.2920842 , -0.51477975, -0.31118087, -0.95

In [61]:
plt.scatter(x,y,c=200*x,s=20+30*y/y.max(),alpha=0.5)

In [62]:
plt.scatter(x,y,c=200*x,s=20+30*y/y.max(),alpha=0.5,label='Fit')

In [63]:
plt.show()

## 6.6 三维图

In [64]:
fig=plt.figure()

In [69]:
ax = fig.gca(projection='3d')  

In [71]:
x=np.linspace(0,10,100)

In [72]:
y=np.linspace(0,10,100)

In [73]:
X,Y=np.meshgrid(x,y)

In [74]:
X

array([[  0.       ,   0.1010101,   0.2020202, ...,   9.7979798,
          9.8989899,  10.       ],
       [  0.       ,   0.1010101,   0.2020202, ...,   9.7979798,
          9.8989899,  10.       ],
       [  0.       ,   0.1010101,   0.2020202, ...,   9.7979798,
          9.8989899,  10.       ],
       ..., 
       [  0.       ,   0.1010101,   0.2020202, ...,   9.7979798,
          9.8989899,  10.       ],
       [  0.       ,   0.1010101,   0.2020202, ...,   9.7979798,
          9.8989899,  10.       ],
       [  0.       ,   0.1010101,   0.2020202, ...,   9.7979798,
          9.8989899,  10.       ]])

In [75]:
Y

array([[  0.       ,   0.       ,   0.       , ...,   0.       ,
          0.       ,   0.       ],
       [  0.1010101,   0.1010101,   0.1010101, ...,   0.1010101,
          0.1010101,   0.1010101],
       [  0.2020202,   0.2020202,   0.2020202, ...,   0.2020202,
          0.2020202,   0.2020202],
       ..., 
       [  9.7979798,   9.7979798,   9.7979798, ...,   9.7979798,
          9.7979798,   9.7979798],
       [  9.8989899,   9.8989899,   9.8989899, ...,   9.8989899,
          9.8989899,   9.8989899],
       [ 10.       ,  10.       ,  10.       , ...,  10.       ,
         10.       ,  10.       ]])

In [76]:
ax.plot_surface(X,Y,X+Y**2)

In [77]:
plt.show()

## 6.7 pandas绘图

In [79]:
df=pd.DataFrame(np.random.randint(0,100,(10,2)))

In [80]:
df

0   1
0  61  91
1  71  23
2  96  85
3  34  31
4  53  28
5  99  91
6  23  50
7   5  33
8  40  60
9  88  28

In [81]:
df.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [82]:
df.index=[1,2,3,4,5,6,7,8,9,10]

In [83]:
df.keys

<bound method DataFrame.keys of      0   1
1   61  91
2   71  23
3   96  85
4   34  31
5   53  28
6   99  91
7   23  50
8    5  33
9   40  60
10  88  28>

In [86]:
df.columns=['f1','f2']

In [87]:
df

f1  f2
1   61  91
2   71  23
3   96  85
4   34  31
5   53  28
6   99  91
7   23  50
8    5  33
9   40  60
10  88  28

In [96]:
df.plot()

In [97]:
plt.show()